Add a CLI arg to CleanUpM2Repository to accept an arbitrary path for the .m2 folder
fasten-project/data-processing pull request #17
Opened 2022-04-25 11:40 UTC by mir-am

This is a very small PR to clean up the .m2 folder at arbitrary paths.
Note that in production we store POM files at a different path not in the home folder as K8s pods store data at `/mnt/fasten/data`.

2022-04-25 23:17 UTC, proksch requested changes
Generally looks good to me, but I have minor requests for renaming.

2022-04-25 23:17 UTC, proksch commented on plugins/pom-analyzer/src/main/java/eu/f4sten/pomanalyzer/CleanUpM2Repository.java
> +        LOG.info("Searching for invalid pom.xml files in: {}", this.args.m2RepositoryPath);
Please avoid unnecessary `this`

2022-04-25 23:17 UTC, proksch commented on plugins/pom-analyzer/src/main/java/eu/f4sten/pomanalyzer/CleanUpM2Repository.java
> +            Files.walkFileTree(Path.of(this.args.m2RepositoryPath), new SimpleFileVisitor<Path>() {
Please avoid unnecessary `this`

2022-04-25 23:17 UTC, proksch commented on plugins/pom-analyzer/src/main/java/eu/f4sten/pomanalyzer/CleanUpM2RepositoryArgs.java
> +    @Parameter(names= "--m2repo.path", arity = 1)
Please rename parameter to `--path.m2`

2022-04-25 23:17 UTC, proksch commented on plugins/pom-analyzer/src/main/java/eu/f4sten/pomanalyzer/CleanUpM2RepositoryArgs.java
> +    public String m2RepositoryPath = "~/.m2/repository";
Please rename field to `pathM2` (to stay consistent with the naming of the argument.)

2022-04-26 06:56 UTC, mir-am commented
Thanks for the comments.
I have addressed them in https://github.com/fasten-project/data-processing/pull/17/commits/d44dd0d4ce03c84c451e545090e4c33740dc3318.

2022-04-27 12:26 UTC, proksch approved these changes

2022-04-27 12:26 UTC, merged